parse = input()
parse = parse.lstrip("*")
parse = parse.rstrip("*")
parse = parse.lstrip("~")
parse = parse.rstrip("~")
parse = parse.lstrip("`")
parse = parse.rstrip("`")
parse = parse.lstrip("_")
parse = parse.rstrip("_")
print(parse)